routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Auth')->middleware(['throttle:20,1'])->group(function () {
    // Banned routes...
    Route::get('ban', 'LoginController@ban')->name('ban');
    // Authentication routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('2fa/form', 'LoginController@show_form_2fa')->name('2fa.form');
    Route::post('2fa/challenge', 'LoginController@challenge_2fa')->name('2fa.challenge');
    Route::post('2fa/login', 'LoginController@login_2fa')->name('2fa.login');
    // Registration routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('register-optional', 'RegisterOptionalController@showForm')->name('register.optional');
    Route::post('register-optional', 'RegisterOptionalController@postForm')->name('register.finalize');
    // Password reset routes...
    Route::get('password/recover', 'PasswordController@showPasswordRecoverForm')->name('password.recover');
    Route::post('password/recover', 'PasswordController@checkUserCredentials');
    Route::get('password/reset/{token}', 'PasswordController@showPasswordResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/change', 'PasswordController@showPasswordChangeForm')->name('password.change');
    Route::post('password/change', 'PasswordController@changePswd');
});

Route::middleware(['throttle:60,1'])->group(function () {
    // public routes
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('intro', 'HomeController@intro')->name('intro');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('contacts', 'HomeController@contacts')->name('contacts');
    Route::post('contacts', 'HomeController@sendMessage')->name('send_msg');
    Route::get('menu', 'HomeController@menu')->name('menu');
    Route::get('api', 'HomeController@api')->name('api');

    // user private routes
    Route::get('home', 'PrivateController@home')->name('home');
    Route::post('changetier', 'UserTierController@generateDepositAddress')->name('changetier');
    Route::post('wallet', 'PrivateController@setRefundWallet')->name('setwallet');
    Route::post('setlanguage', 'PrivateController@setLanguage')->name('setlanguage');
    Route::post('actas', 'PrivateController@actingAsUser')->name('set_actas');
    Route::get('markasread/{id}', 'PrivateController@markAsRead')->name('markasread');
    Route::post('addpgp', 'PrivateController@addPgpKey')->name('addpgp');
    Route::get('removepgp', 'PrivateController@removePgpKey')->name('removepgp');
    Route::get('enable2fa', 'PrivateController@enable2fa')->name('enable_2fa');
    Route::get('disable2fa', 'PrivateController@disable2fa')->name('disable_2fa');

    // tokens
    Route::get('tokens', 'TokenController@index')->name('tokens.index');
    Route::delete('tokens/{token}', 'TokenController@destroy')->name('tokens.delete');
    Route::get('tokens/revoke/{token}', 'TokenController@revoke')->name('tokens.revoke');

    // cancel payments
    Route::post('/payments/cancel/{payment}', 'PaymentRequestController@cancel')->name('payments.cancel');

    // resource controllers
    Route::resource('users', 'UserController');
    Route::resource('payments', 'PaymentRequestController');
    Route::resource('disputes', 'DisputeController');
    Route::resource('coupons', 'CouponController');
    Route::resource('tickets', 'TicketController');
    Route::resource('merchants', 'MerchantController');
    Route::resource('marketplaces', 'MarketplaceController');

    // merchant wallet
    Route::post('merchants/wallet', 'MerchantController@setPersonalWallet')->name('merchant.setwallet');

    // marketplace wallet
    Route::post('marketplaces/wallet', 'MarketplaceController@setWallet')->name('marketplace.setwallet');

    // checkout process
    Route::prefix('checkout')->group(function () {
        Route::get('/review/{payment}', 'CheckoutController@review')->name('checkout.review');
        Route::get('/wallet/{payment}', 'CheckoutController@wallet')->name('checkout.wallet');
        Route::get('/currency/{payment}', 'CheckoutController@currency')->name('checkout.currency');
        Route::get('/pay/{payment}/{cryptocurrency}', 'CheckoutController@pay')->name('checkout.pay');
        Route::get('/verify/{payment}', 'CheckoutController@verify')->name('checkout.verify');
        Route::post('/coupon', 'CheckoutController@coupon')->name('checkout.coupon');
        Route::get('/success', 'CheckoutController@successPage')->name('checkout.success');
        Route::get('/cancel', 'CheckoutController@cancelPage')->name('checkout.cancel');
        Route::get('/expired', 'CheckoutController@expiredPage')->name('checkout.expired');
    });

    Route::namespace('Admin')->middleware(['staff'])->prefix('admin')->group(function () {
        Route::get('/online', 'AdminController@online')->name('admin.online');
        Route::get('/offline', 'AdminController@offline')->name('admin.offline');
        Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
        Route::get('/interactions', 'AdminController@interactions')->name('admin.interactions');
        Route::get('/messages', 'AdminController@messages')->name('admin.messages');
        Route::get('/logs', 'LogsController@index')->name('admin.logs');
        Route::get('/logs/clear', 'LogsController@clear')->name('admin.clearlogs');

        // news
        Route::get('/news', 'AdminNewsController@index')->name('admin.news.index');
        Route::get('/news/create', 'AdminNewsController@create')->name('admin.news.create');
        Route::post('/news', 'AdminNewsController@store')->name('admin.news.store');
        Route::delete('/news/{news}', 'AdminNewsController@destroy')->name('admin.news.destroy');
        // users
        Route::get('/users', 'AdminUserController@index')->name('admin.users.index');
        Route::get('/users/show/{user}', 'AdminUserController@show')->name('admin.users.show');
        Route::get('/users/removed', 'AdminUserController@removed')->name('admin.users.removed');
        Route::get('/users/restore/{id}', 'AdminUserController@restore')->name('admin.users.restore');
        Route::get('/users/merchant/{user}', 'AdminUserController@makeMerchant')->name('admin.users.makemerchant');
        Route::get('/users/marketplace/{user}', 'AdminUserController@makeMarketplace')->name('admin.users.makemarketplace');
        Route::get('/ban/{user}', 'AdminUserController@ban')->name('admin.users.ban');
        Route::get('/unban/{user}', 'AdminUserController@unban')->name('admin.users.unban');
        // disputes
        Route::get('/disputes', 'AdminDisputeController@index')->name('admin.disputes.index');
        Route::get('/disputes/review', 'AdminDisputeController@review')->name('admin.disputes.review');
        Route::get('/disputes/show/{dispute}', 'AdminDisputeController@show')->name('admin.disputes.show');
        Route::get('/disputes/accept/{dispute}', 'AdminDisputeController@accept')->name('admin.disputes.accept');
        Route::get('/disputes/reject/{dispute}', 'AdminDisputeController@reject')->name('admin.disputes.reject');
        // payments
        Route::get('/payments', 'AdminPaymentController@index')->name('admin.payments.index');
        Route::get('/payments/reported', 'AdminPaymentController@reported')->name('admin.payments.reported');
        Route::get('/payments/show/{payment}', 'AdminPaymentController@show')->name('admin.payments.show');
        // tickets
        Route::get('/tickets', 'AdminTicketController@index')->name('admin.tickets.index');
        Route::get('/tickets/open', 'AdminTicketController@open')->name('admin.tickets.open');
        Route::get('/tickets/show/{ticket}', 'AdminTicketController@show')->name('admin.tickets.show');
        Route::get('/tickets/change/status/{ticket}/{status}', 'AdminTicketController@changeStatus')->name('admin.tickets.changestatus');
        Route::get('/tickets/change/priority/{ticket}/{priority}', 'AdminTicketController@changePriority')->name('admin.tickets.changepriority');
        // cryptocurrencies
        Route::get('/cryptocurrencies', 'AdminCryptocurrencyController@index')->name('admin.cryptocurrencies.index');
        Route::get('/cryptocurrencies/create', 'AdminCryptocurrencyController@create')->name('admin.cryptocurrencies.create');
        Route::post('/cryptocurrencies', 'AdminCryptocurrencyController@store')->name('admin.cryptocurrencies.store');
        Route::get('/cryptocurrencies/edit/{cryptocurrency}', 'AdminCryptocurrencyController@edit')->name('admin.cryptocurrencies.edit');
        Route::post('/cryptocurrencies/update/{cryptocurrency}', 'AdminCryptocurrencyController@update')->name('admin.cryptocurrencies.update');
        Route::delete('/cryptocurrencies/{cryptocurrency}', 'AdminCryptocurrencyController@destroy')->name('admin.cryptocurrencies.destroy');

        //Route::diskMonitor('/disks');
    });

    // oauth passport
    Route::prefix('oauth')->middleware(['merchant'])->group(function () {
        Route::get('/authorize', '\Laravel\Passport\Http\Controllers\AuthorizationController@authorize')->name('passport.authorizations.authorize');
        Route::post('/authorize', 'OauthController@approve')->name('passport.authorizations.approve');

resources/views/about.blade.php
@extends('layouts.app')

@section('content')

<!-- Main -->
<div id="main">

    <a href="{{ route('index') }}" target="_self" title="home"><i class="icss-x x2"></i></a>

    <!-- Intro -->
    <article id="intro">
        <h2 class="major">About</h2>
        <section>
            <p>Beyond this project there is an active group of enthusiasts users who, tired of the several exit scams, 
                continuous and tiresome need to migrate from market to market and loss of funds, decided to create a platform
                to facilitate commercial exchanges online.</p>
            <p>We are a group of developers, security advisors and hackers, all anonymous but active on the majour platforms like Dread or Torch,
                committed to guarantee a professional service at extremely low prices, barely enough to cover maintenance costs and infrastructure.</p>
            <p>There is no limit to what you can trade, we don't have a code of conduct or terms of service except the basic rule of safeguarding a 
                productive and helpful space for both clients and merchants where scams are not allowed and persecuted.
            </p>
        </section>
        <section>
            <h3 class="major">Timeline</h3>
            <ol>
                <li><i>February 2020</i> - {{ config('app.name') }} was launched</li>
            </ol>
        </section>
    </article>
</div>

@endsection

resources/views/api.blade.php
@extends('layouts.app')

@section('content')

<!-- Main -->
<div id="main">

    <a href="{{ route('index') }}" target="_self" title="home"><i class="icss-x x2"></i></a>

    <!-- Intro -->
    <article id="intro">
        <h2 class="major">API Documentation</h2>
        <section>
            <p>Here is a summary of all avaliable APIs.</p>
            <p>Endpoint: <b>{{ config('app.url').'/api/v1/' }}</b></p>
            <p>All requests must have the <code>Accept: application/json</code> header as well as use the <code>Authorization: Bearer '...'</code>
               token.
            </p>
            <p>{{ config('app.name') }} runs a fully-fledged Oauth2 server, merchants have their own API tokens
                while they can allow marketplaces to access and manage payment requests via cross authorization.<br>
            </p>
        </section>

        <hr>

        <!-- endpoint GET /payments -->
        <section>
            <h3 class="major">[GET] /payments</h3>
            <p>Get data about all payments related to the user</p>
            <h4>Example</h4>
            <pre><code>
$ curl {{ config('app.url') }}/api/v1/payments \
  -X POST \
  -H "Accept: application/json" \
  -H "Authorization: Bearer TOKEN"
            </code></pre>
            <h4>Sample Response</h4>
            <pre><code>{
    "message": [
        {
            "id": "92efc018-a398-12p9-la1b-ce6e3b7788d4",
            "orderid": null,
            "whoami": "MERCHANT",
            "merchant": "someuser",
            "amount_usd": "12.00",
            "shipping_usd": "2.00",
            ... 
        }
    ]
}</code></pre>
            <h4>Response Data</h4>
            <p>see below for info</p>
        </section>

        <hr>

        <!-- endpoint GET /payments/:id -->
        <section>
            <h3 class="major">[GET] /payments/:id</h3>
            <p>Get data about a specific payment</p>
            <h4>URL Parameters</h4>
            <table class="alt">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>id</td>
                        <td>Unique key of the payment (UUID)</td>
                    </tr>
                </tbody>
            </table>
            <h4>Example</h4>
            <pre><code>
$ curl {{ config('app.url') }}/api/v1/payments/923cf45b-8da1-4a57-98fa-36687adec41b \
  -X POST \
  -H "Accept: application/json" \
  -H "Authorization: Bearer TOKEN"
            </code></pre>
            <h4>Sample Response</h4>
            <pre><code>
{
    "id": "92cfc047-a398-46e6-ba1b-da6e3b7785d4",
    "orderid": "Al902p",
    "whoami": "MERCHANT",
    "merchant": "testmerchant",
    "amount_usd": "12.00",
    "shipping_usd": "12.00",
    "goods_type": "DIGITAL",
    "payment_type": "ESCROW",
    "url": "{{ config('app.url') }}/checkout/review/92lop047-a398-46e6-ca1s-da6f3b1930d4?expires=1601814618&signature=c5c361e9311d409095bfef140da9143a2f9fb39f0cd50147108396c72a42c11b",
    "status": "PENDING",
    "expires_at": "2021-02-01T00:00:00.000000Z",
    "created_at": "2021-01-01T00:00:00.000000Z",
    "updated_at": "2021-01-24T00:00:00.000000Z",
    "description": "a test payment",
    "marketplace": "testmarketplace",
    "customer": "testcustomer",
    "notes": null
}</code></pre>
            <h4>Response Data</h4>
            <p>Fields marked with * may be null or not present</p>
            <table class="alt">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>id</td>
                        <td>Unique key of the payment (UUID)</td>
                    </tr>
                    <tr>
                        <td>orderid*</td>
                        <td>A custom ID for the payment</td>
                    </tr>
                    <tr>
                        <td>whoami</td>
                        <td>Whether the user sending the request is a customer or a merchant</td>
                    </tr>
                    <tr>
                        <td>customer*</td>
                        <td>The customer linked to the payment</td>
                    </tr>
                    <tr>
                        <td>merchant</td>
                        <td>The merchant requesting the payment</td>
                    </tr>
                    <tr>
                        <td>marketplace*</td>
                        <td>The marketplace requesting the payment on behalf of the merchant</td>
                    </tr>
                    <tr>
                        <td>amount_usd</td>
                        <td>The items price in USD</td>
                    </tr>
                    <tr>
                        <td>shipping_usd</td>
                        <td>The shipping price in USD</td>
                    </tr>
                    <tr>
                        <td>goods_type</td>
                        <td>The type of goods (PHYSICAL => 30, DIGITAL => 31 or SERVICES => 32)</td>
                    </tr>
                    <tr>
                        <td>payment_type</td>
                        <td>The type of payment (ESCROW => 60 or FE (finalize early) => 61)</td>
                    </tr>
                    <tr>
                        <td>url</td>
                        <td>The checkout URL to redirect the customer to</td>
                    </tr>
                    <tr>
                        <td>status</td>
                        <td>The payment status</td>
                    </tr>
                    <tr>
                        <td>description</td>
                        <td>The payment description in text format</td>
                    </tr>
                    <tr>
                        <td>coupon*</td>
                        <td>Coupon applied</td>
                    </tr>
                    <tr>
                        <td>discount*</td>
                        <td>Discount applied</td>
                    </tr>
                    <tr>
                        <td>notes*</td>
                        <td>Customer notes</td>
                    </tr>
                    <tr>
                        <td>expires_at</td>
                        <td>The payment expiration date</td>
                    </tr>
                    <tr>
                        <td>created_at</td>
                        <td>The payment creation timestamp</td>
                    </tr>
                    <tr>
                        <td>updated_at</td>
                        <td>The payment last update timestamp</td>
                    </tr>
                </tbody>
            </table>
            <h4>States</h4>
            <p>Possible states for a ESCROW payment object are:</p>
            <ul>
                <li>"PENDING" - the payment is still unconfirmed and/or unlinked to a specific customer</li>
                <li>"CONFIRMING" - funds have been sent by the user but the transaction is still unconfirmed</li>
                <li>"FUNDED" - funds have been received, the payment is now confirmed</li>
                <li>"CANCELLED" - payment has been cancelled by the merchant</li>
                <li>"EXPIRED" - funds haven't been sent and the payment expired</li>
                <li>"CLOSED" - the payment has been closed and cannot be further modified</li>
                <li>"REFUNDED" - a refund was issued by the merchant, funds have been sent back to the customer</li>
                <li>"REPORTED" - a dispute has been opened and a moderator will review it</li>
                <li>"CUSTOMER_PAYOUT" - the moderator decided in favour of the customer</li>
                <li>"MERCHANT_PAYOUT" - the moderator decided in favour of the merchant</li>
            </ul>
            <p>Possible states for a FE payment object are:</p>
            <ul>
                <li>"PENDING" - the payment is still unconfirmed and/or unlinked to a specific customer</li>
                <li>"CONFIRMING" - funds have been sent by the user but the transaction is still unconfirmed</li>
                <li>"CLOSED" - the payment has been closed and cannot be further modified</li>
            </ul>
            <p>FE payments are direct and no moderation is possible</p>
        </section>

        <hr>

        <!-- endpoint POST /payments -->
        <section>
            <h3 class="major">[POST] /payments</h3>
            <p>Create a new payment request</p>
            <h4>Parameters</h4>
            <p>Those with * are optional</p>
            <table class="alt">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>orderid*</td>
                        <td>A custom ID for the payment</td>
                    </tr>
                    <tr>
                        <td>amount_usd</td>
                        <td>The items price in USD</td>
                    </tr>
                    <tr>
                        <td>shipping_usd</td>
                        <td>The shipping price in USD</td>
                    </tr>
                    <tr>
                        <td>goods_type</td>
                        <td>The type of goods (PHYSICAL => 30, DIGITAL => 31 or SERVICES => 32)</td>
                    </tr>
                    <tr>
                        <td>payment_type</td>
                        <td>The type of payment (ESCROW => 60 or FE (finalize early) => 61)</td>
                    </tr>
                    <tr>
                        <td>description</td>
                        <td>The payment description in text format</td>
                    </tr>
                </tbody>
            </table>
            <h4>Example</h4>
            <pre><code>
$ curl {{ config('app.url') }}/api/v1/payments \
  -X POST \
  -H "Accept: application/json" \
  -H "Authorization: Bearer TOKEN" \
  -d '{
        "orderid": "ABy32k",
        "amount_usd": 12.11,
        "shipping_usd" => 1.99,
        "goods_type" => 30,
        "payment_type" => 60,
        "description" => "test payment",
    }'
</code></pre>
            <h4>Response</h4>
            <p>A 200 status and the JSON-encoded printout of the newly-created payment request</p>
        </section>

        <hr>

        <!-- endpoint POST /tokens -->
        <section>
            <h3 class="major">[POST] /tokens</h3>
            <p>Create a new OAuth token</p>
            <h4>Parameters</h4>
            <table class="alt">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>client_id</td>
                        <td>A custom ID for the client</td>
                    </tr>
                    <tr>
                        <td>client_secret</td>
                        <td>The shared secret between the client and the server</td>
                    </tr>
                    <tr>
                        <td>grant_type</td>
                        <td>Should be set to 'authorization_code'</td>
                    </tr>
                    <tr>
                        <td>redirect_uri</td>
                        <td>The callback url to return the token to</td>
                    </tr>
                    <tr>
                        <td>code</td>
                        <td>The code obtained by the /authorize API call</td>
                    </tr>
                </tbody>
            </table>
            <h4>Example</h4>
            <pre><code>
        $ curl {{ config('app.url') }}/api/v1/tokens \
        -X POST \
        -H "Accept: application/json" \
        -d '{
        "code": "dab...",
        "redirect_uri": 'http://callback.com',
        "grant_type" => 'authorization_code',
        "client_id" => 30,
        "client_secret" => '...',
        }'
        </code></pre>
            <h4>Response</h4>
            <p>A 200 status and the JSON-encoded printout of the newly-created payment request</p>
        </section>

    </article>
</div>

@endsection

resources/views/captcha.blade.php
@extends('layouts.app')

@section('content')
<!-- Main -->
<div id="main">

    <a href="{{ route('index') }}" target="_self" title="home"><i class="icss-x x2"></i></a>

    <!-- Contact -->
    <article id="contact">
        <section>
            <h2 class="major">Entrance Gate</h2>
            <h4>This is a humans only club, no robots allowed!</h4>
            <p>Solve this simple math question, <b>ignore the last operation</b></p>
            <h2>{{ $question }} - {{ rand(1,10) }} =</h2>
            <form action="{{ route('riddle') }}" method="POST">
            @csrf
            {!! $input !!}
            <br>
            <input type="submit" value="Submit" class="primary">
            @honeypot
            </form>
        </section>
    </article>

</div>
@endsection

resources/views/contacts.blade.php
@extends('layouts.app')

@section('content')
<!-- Main -->
<div id="main">

    <a href="{{ route('index') }}" target="_self" title="home"><i class="icss-x x2"></i></a>

    <!-- Contact -->
    <article id="contact">
        <section>
            <h2 class="major">Contacts</h2>
            <h4>PGP Key</h4>
            <pre><code>
pgp
            </code></pre>
        </section>
        <section>
            @if(count($errors) > 0)
            <h3 class="major">Errors</h3>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @elseif(session()->has('message'))
            <h4>{{ session()->get('message') }}</h4>
            @endif
            <form method="POST" action="{{ route('send_msg') }}">
            @csrf
                <div class="fields">
                    <div class="field half">
                        <label for="contact">Contact</label>
                        <input type="text" name="contact" id="contact" maxlength="100" placeholder="someone@said.hello" required>
                    </div>
                    <div class="field half">
                        <label for="contact_type">Contact Channel</label>
                        <input type="text" name="contact_type" id="contact_type" maxlength="200" placeholder="specify jabber/email/telegram/..." required>
                    </div>
                    <div class="field">
                        <label for="body">Message</label>
                        <textarea name="body" id="body" rows="4" minlength="10" maxlength="1000" placeholder="Everything starts with one word..." required></textarea>
                    </div>
                    <div class="field">
                        <label for="demo-category">Are you a human?</label>
                        <select name="robot" id="robot" required>
                            <option value="">-</option>
                            <option value="1">Yes</option>
                            <option value="2">No</option>
                            <option value="3">Maybe</option>
                        </select>
                    </div>
                </div>
                <ul class="actions">
                    <li><input type="submit" value="Send Message" class="primary"></li>
                    <li><input type="reset" value="Reset"></li>
                </ul>
            @honeypot
            </form>
        </section>
    </article>

</div>
@endsection

resources/views/menu.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, shrink-to-fit=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">

            <title>{{ config('app.name') }}</title>

        <link rel="shortcut icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">
        <link rel="icon" href="{{ asset('images/favicon.ico') }}" type="image/x-icon">

        <link href="{{ asset('css/all.css') }}" rel="stylesheet">
        <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ asset('css/private.css') }}" rel="stylesheet">
        <link href="{{ asset('css/floating.css') }}" rel="stylesheet">

        <style>
        .menuButton {
        padding:20px 0;
        display:block;
        z-index: 12;
        }

        .btn {
        display:block;
        height:7px;
        width:50px;
        z-index:12;
        margin-left:10px;
        background:#fff;
        position:relative;
        -moz-transition-duration: .2s;
        -o-transition-duration: .2s;
        -webkit-transition-duration: .2s;
        transition-duration: .2s;
        }

        .btn::before {
            content:'';
            position:absolute;
            top:-15px;
            left:0;
            width:50px;
            height:7px;
            background:#fff;
            -moz-transition-duration: .2s;
            -o-transition-duration: .2s;
            -webkit-transition-duration: .2s;
            transition-duration: .2s;
        }
        
        .btn::after {
            content:'';
            position:absolute;
            top:15px;
            left:0;
            width:50px;
            height:7px;
            background:#fff;
            -moz-transition-duration: .2s;
            -o-transition-duration: .2s;
            -webkit-transition-duration: .2s;
            transition-duration: .2s;
        }


        .activeBtn {
        background:transparent;
        }

        .activeBtn::before {
            -webkit-transform:rotate(45deg);
            top:0;
        }
        
        .activeBtn::after {
            -webkit-transform:rotate(-45deg);
            top:0;
        }

        #overmenu{
            position: fixed;
            top:0;
            left:-1%;
            background:#EC6B56;
            width:101%;
            margin-left:+=101%;
            height:100%;
            z-index: 10;
            opacity:1;
        }

        #overmenu span{
            padding:5px 7px;
        }

        #overmenu ul {
            position: relative;
            top: 50%;
            -webkit-transform: translateY(-50%);
            -ms-transform: translateY(-50%);
            transform: translateY(-50%);
        }

        #overmenu a {
            color:#fff;
            font-size: 50px;
            font-weight: bold;
            text-decoration:none;
        }

        #overmenu span:hover {
            background:#fff;
            color: #4e657a;
        }

        #overmenu li {
            list-style: none;
            padding: 10px;
            margin-bottom: 5%;
            text-align: center;
        }
        </style>
    </head>
    
    <body id="reportsPage">

        <a class="menuButton" href="{{ url(session()->pull('_previous')['url']) }}">
            <div class="btn activeBtn"></div>
        </a>
        <div id="overmenu">
        <ul>
            <li><a href="{{ route('home') }}"><span>Dashboard</span></a></li>
            <li><a href="{{ route('payments.index') }}"><span>Payments</span></a></li>
            <li><a href="{{ route('disputes.index') }}"><span>Disputes</span></a></li>
            @if($currentUser->isMerchant())
            <li><a href="{{ route('merchants.show', $currentUser->merchant) }}"><span>Merchant</span></a></li>
            @elseif($currentUser->isStaff() || $currentUser->isAdmin())
            <li><a href="{{ route('admin.dashboard') }}"><span>Manage</span></a></li>
            @endif
            <li><a href="{{ route('users.show', $currentUser) }}"><span>My Account</span></a></li>
            <li><a href="{{ route('logout') }}"><span>Logout</span></a></li>
        </ul>
        </div>

    </body>
</html>