routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Auth')->middleware(['throttle:20,1'])->group(function () {
    // Banned routes...
    Route::get('ban', 'LoginController@ban')->name('ban');
    // Authentication routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('2fa/form', 'LoginController@show_form_2fa')->name('2fa.form');
    Route::post('2fa/challenge', 'LoginController@challenge_2fa')->name('2fa.challenge');
    Route::post('2fa/login', 'LoginController@login_2fa')->name('2fa.login');
    // Registration routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('register-optional', 'RegisterOptionalController@showForm')->name('register.optional');
    Route::post('register-optional', 'RegisterOptionalController@postForm')->name('register.finalize');
    // Password reset routes...
    Route::get('password/recover', 'PasswordController@showPasswordRecoverForm')->name('password.recover');
    Route::post('password/recover', 'PasswordController@checkUserCredentials');
    Route::get('password/reset/{token}', 'PasswordController@showPasswordResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/change', 'PasswordController@showPasswordChangeForm')->name('password.change');
    Route::post('password/change', 'PasswordController@changePswd');
});

Route::middleware(['throttle:60,1'])->group(function () {
    // public routes
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('intro', 'HomeController@intro')->name('intro');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('contacts', 'HomeController@contacts')->name('contacts');
    Route::post('contacts', 'HomeController@sendMessage')->name('send_msg');
    Route::get('menu', 'HomeController@menu')->name('menu');
    Route::get('api', 'HomeController@api')->name('api');

    // user private routes
    Route::get('home', 'PrivateController@home')->name('home');
    Route::post('changetier', 'UserTierController@generateDepositAddress')->name('changetier');
    Route::post('wallet', 'PrivateController@setRefundWallet')->name('setwallet');
    Route::post('setlanguage', 'PrivateController@setLanguage')->name('setlanguage');
    Route::post('actas', 'PrivateController@actingAsUser')->name('set_actas');
    Route::get('markasread/{id}', 'PrivateController@markAsRead')->name('markasread');
    Route::post('addpgp', 'PrivateController@addPgpKey')->name('addpgp');
    Route::get('removepgp', 'PrivateController@removePgpKey')->name('removepgp');
    Route::get('enable2fa', 'PrivateController@enable2fa')->name('enable_2fa');
    Route::get('disable2fa', 'PrivateController@disable2fa')->name('disable_2fa');

    // tokens
    Route::get('tokens', 'TokenController@index')->name('tokens.index');
    Route::delete('tokens/{token}', 'TokenController@destroy')->name('tokens.delete');
    Route::get('tokens/revoke/{token}', 'TokenController@revoke')->name('tokens.revoke');

    // cancel payments
    Route::post('/payments/cancel/{payment}', 'PaymentRequestController@cancel')->name('payments.cancel');

    // resource controllers
    Route::resource('users', 'UserController');
    Route::resource('payments', 'PaymentRequestController');
    Route::resource('disputes', 'DisputeController');
    Route::resource('coupons', 'CouponController');
    Route::resource('tickets', 'TicketController');
    Route::resource('merchants', 'MerchantController');
    Route::resource('marketplaces', 'MarketplaceController');

    // merchant wallet
    Route::post('merchants/wallet', 'MerchantController@setPersonalWallet')->name('merchant.setwallet');

    // marketplace wallet
    Route::post('marketplaces/wallet', 'MarketplaceController@setWallet')->name('marketplace.setwallet');

    // checkout process
    Route::prefix('checkout')->group(function () {
        Route::get('/review/{payment}', 'CheckoutController@review')->name('checkout.review');
        Route::get('/wallet/{payment}', 'CheckoutController@wallet')->name('checkout.wallet');
        Route::get('/currency/{payment}', 'CheckoutController@currency')->name('checkout.currency');
        Route::get('/pay/{payment}/{cryptocurrency}', 'CheckoutController@pay')->name('checkout.pay');
        Route::get('/verify/{payment}', 'CheckoutController@verify')->name('checkout.verify');
        Route::post('/coupon', 'CheckoutController@coupon')->name('checkout.coupon');
        Route::get('/success', 'CheckoutController@successPage')->name('checkout.success');
        Route::get('/cancel', 'CheckoutController@cancelPage')->name('checkout.cancel');
        Route::get('/expired', 'CheckoutController@expiredPage')->name('checkout.expired');
    });

    Route::namespace('Admin')->middleware(['staff'])->prefix('admin')->group(function () {
        Route::get('/online', 'AdminController@online')->name('admin.online');
        Route::get('/offline', 'AdminController@offline')->name('admin.offline');
        Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
        Route::get('/interactions', 'AdminController@interactions')->name('admin.interactions');
        Route::get('/messages', 'AdminController@messages')->name('admin.messages');
        Route::get('/logs', 'LogsController@index')->name('admin.logs');
        Route::get('/logs/clear', 'LogsController@clear')->name('admin.clearlogs');

        // news
        Route::get('/news', 'AdminNewsController@index')->name('admin.news.index');
        Route::get('/news/create', 'AdminNewsController@create')->name('admin.news.create');
        Route::post('/news', 'AdminNewsController@store')->name('admin.news.store');
        Route::delete('/news/{news}', 'AdminNewsController@destroy')->name('admin.news.destroy');
        // users
        Route::get('/users', 'AdminUserController@index')->name('admin.users.index');
        Route::get('/users/show/{user}', 'AdminUserController@show')->name('admin.users.show');
        Route::get('/users/removed', 'AdminUserController@removed')->name('admin.users.removed');
        Route::get('/users/restore/{id}', 'AdminUserController@restore')->name('admin.users.restore');
        Route::get('/users/merchant/{user}', 'AdminUserController@makeMerchant')->name('admin.users.makemerchant');
        Route::get('/users/marketplace/{user}', 'AdminUserController@makeMarketplace')->name('admin.users.makemarketplace');
        Route::get('/ban/{user}', 'AdminUserController@ban')->name('admin.users.ban');
        Route::get('/unban/{user}', 'AdminUserController@unban')->name('admin.users.unban');
        // disputes
        Route::get('/disputes', 'AdminDisputeController@index')->name('admin.disputes.index');
        Route::get('/disputes/review', 'AdminDisputeController@review')->name('admin.disputes.review');
        Route::get('/disputes/show/{dispute}', 'AdminDisputeController@show')->name('admin.disputes.show');
        Route::get('/disputes/accept/{dispute}', 'AdminDisputeController@accept')->name('admin.disputes.accept');
        Route::get('/disputes/reject/{dispute}', 'AdminDisputeController@reject')->name('admin.disputes.reject');
        // payments
        Route::get('/payments', 'AdminPaymentController@index')->name('admin.payments.index');
        Route::get('/payments/reported', 'AdminPaymentController@reported')->name('admin.payments.reported');
        Route::get('/payments/show/{payment}', 'AdminPaymentController@show')->name('admin.payments.show');
        // tickets
        Route::get('/tickets', 'AdminTicketController@index')->name('admin.tickets.index');
        Route::get('/tickets/open', 'AdminTicketController@open')->name('admin.tickets.open');
        Route::get('/tickets/show/{ticket}', 'AdminTicketController@show')->name('admin.tickets.show');
        Route::get('/tickets/change/status/{ticket}/{status}', 'AdminTicketController@changeStatus')->name('admin.tickets.changestatus');
        Route::get('/tickets/change/priority/{ticket}/{priority}', 'AdminTicketController@changePriority')->name('admin.tickets.changepriority');
        // cryptocurrencies
        Route::get('/cryptocurrencies', 'AdminCryptocurrencyController@index')->name('admin.cryptocurrencies.index');
        Route::get('/cryptocurrencies/create', 'AdminCryptocurrencyController@create')->name('admin.cryptocurrencies.create');
        Route::post('/cryptocurrencies', 'AdminCryptocurrencyController@store')->name('admin.cryptocurrencies.store');
        Route::get('/cryptocurrencies/edit/{cryptocurrency}', 'AdminCryptocurrencyController@edit')->name('admin.cryptocurrencies.edit');
        Route::post('/cryptocurrencies/update/{cryptocurrency}', 'AdminCryptocurrencyController@update')->name('admin.cryptocurrencies.update');
        Route::delete('/cryptocurrencies/{cryptocurrency}', 'AdminCryptocurrencyController@destroy')->name('admin.cryptocurrencies.destroy');

        //Route::diskMonitor('/disks');
    });

    // oauth passport
    Route::prefix('oauth')->middleware(['merchant'])->group(function () {
        Route::get('/authorize', '\Laravel\Passport\Http\Controllers\AuthorizationController@authorize')->name('passport.authorizations.authorize');
        Route::post('/authorize', 'OauthController@approve')->name('passport.authorizations.approve');
        Route::delete('/authorize', '\Laravel\Passport\Http\Controllers\DenyAuthorizationController@deny')->name('passport.authorizations.deny');
    });

});

// autodestruction

resources/views/payments/create.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">

        <!-- col -->
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title text-center">{{ __('Create New Payment Request') }}</h2>
                <form method="POST" action="{{ route('payments.store') }}" class="tm-login-form">
                @csrf

                    <!-- Description -->
                    <div class="form-group">
                        <label for="description">{{ __('Description') }}</label>
                        <textarea id="description" name="description" class="form-control validate @error('description') is-invalid @enderror h-25" rows="5" required>{{ old('description') }}</textarea>
                        @error('description')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <!-- Amount -->
                    <div class="form-group">
                        <label for="amount_usd">{{ __('Amount') }}&nbsp;(USD)</label>
                        <input id="amount_usd" name="amount_usd" type="number" class="form-control validate @error('amount_usd') is-invalid @enderror" value="{{ old('amount_usd') }}" min="0" max="99999999" required>
                        @error('amount_usd')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <!-- Shipping -->
                    <div class="form-group">
                        <label for="shipping_usd">{{ __('Shipping') }} (USD)</label>
                        <input id="shipping_usd" name="shipping_usd" type="number" class="form-control validate @error('shipping_usd') is-invalid @enderror" value="{{ old('shipping_usd') }}" min="0" max="99999999" required>
                        @error('shipping_usd')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <!-- Goods Type -->
                    <div class="form-group">
                        <label for="goods_type">{{ __('Type of Goods') }}</label>
                        <select id="goods_type" name="goods_type" class="custom-select validate @error('goods_type') is-invalid @enderror" required>
                            <option>{{ __('Choose') }}...</option>
                            @foreach($types as $key => $type)
                            <option value="{{ $key }}"
                            @if(old('goods_type') == $key)
                            selected
                            @endif
                            >{{ strtoupper($type) }}</option>
                            @endforeach
                        </select>
                        @error('goods_type')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <!-- Payment Type -->
                    <div class="form-group">
                        <label for="payment_type">{{ __('Type of Payment') }}</label>
                        <select id="payment_type" name="payment_type" class="custom-select validate @error('payment_type') is-invalid @enderror" required>
                            <option>{{ __('Choose') }}...</option>
                            @foreach($payment_types as $key => $payment_type)
                            <option value="{{ $key }}"
                            @if(old('payment_type') == $key)
                            selected
                            @endif
                            >{{ strtoupper($payment_type) }}</option>
                            @endforeach
                        </select>
                        @error('payment_type')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Add') }}</button>
                    </div>
                @honeypot
                </form>
            </div>
        </div>
        <!-- /.col -->

    </div>
    <!-- /.row -->
@endsection

resources/views/payments/index.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">Payments registered</h2>
                    <table class="table table-hover tm-table-small tm-product-table">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                @if($currentUser->isMerchant())
                                <th scope="col">{{ __('CLIENT ID') }}</th>
                                @else
                                <th scope="col">{{ __('MERCHANT') }}</th>
                                @endif
                                <th scope="col">{{ __('AMOUNT') }}&nbsp;(USD)</th>
                                <th scope="col">{{ __('STATUS') }}</th>
                                <th scope="col">{{ __('TYPE') }}</th>
                                <th scope="col">{{ __('DATE') }}</th>
                                <th scope="col">{{ __('DISPUTE') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($payment_requests as $payment)
                            <tr>
                                <td scope="row"><b><a style="color: white" href="{{ route('payments.show', $payment->id) }}">{{ $payment->id }}</a></b></td>
                                @if($currentUser->isMerchantInPayment($payment))
                                    @if($payment->user != null)
                                    <td>{{ $payment->user->username }}</td>
                                    @else
                                    <td>-</td>
                                    @endif
                                @else
                                <td>{{ $payment->merchant->user->username }}</td>
                                @endif
                                <td>${{ $payment->getFinalPrice() }}</td>
                                <td>{{ strtoupper($payment->status) }}</td>
                                <td>{{ $payment->payment_type->key }}</td>
                                <td>{{ $payment->created_at->format('m/d/Y') }}</td>
                                <td>
                                    @if( isset($payment->dispute) )
                                        <a class="tm-product-delete-link" href="{{ route('disputes.show', $payment->dispute->id) }}">
                                            <i class="icss-gavel tm-product-delete-icon"></i>
                                        </a>
                                    @elseif(!$currentUser->isMerchantInPayment($payment) && $payment->isEscrow() && $payment->isFunded())
                                        <form action="{{ route('disputes.create') }}" method="GET">
                                        @csrf
                                            <input name="payment_id" id="payment_id" type="hidden" value="{{ $payment->id }}">

                                            <button class="tm-product-delete-link" type="submit">
                                                <i class="icss-flag tm-product-delete-icon"></i>
                                            </button>
                                        @honeypot
                                        </form>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                @if($currentUser->isMerchant())
                <hr>
                <!-- table container -->
                <a href="{{ route('payments.create') }}" class="btn btn-primary btn-block text-uppercase mb-3" title="{{ __('Create New Payment Request') }}">{{ __('Create New Payment Request') }}</a>
                <!--<button class="btn btn-primary btn-block text-uppercase">Delete selected</button>-->
                @endif
            </div>
        </div>

        @if($currentUser->isMerchant())
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Coupons') }}</h2>
                    <table class="table tm-table-small tm-product-table">
                        <thead>
                            <tr>
                                <th scope="col">{{ __('CODE') }}</th>
                                <th scope="col">{{ __('DISCOUNT') }}</th>
                                <th scope="col">{{ __('USED') }}</th>
                                <th scope="col">{{ __('EXPIRATION') }}</th>
                                <th scope="col">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($coupons as $coupon)
                            <tr>
                                <td class="tm-product-name">{{ $coupon->code }}</td>
                                <td>{{ $coupon->discount }}%</td>
                                <td>{{ $coupon->users()->count() }}/{{ $coupon->usage_limit }}</td>
                                <td>{{ $coupon->expires_at->format('m/d/Y') }}</td>
                                <td class="text-center">
                                    <form action="{{ route('coupons.destroy', $coupon->id) }}" method="POST">
                                    @csrf
                                        <input name="_method" type="hidden" value="DELETE">
                                        <button class="tm-product-delete-link" type="submit">
                                            <i class="icss-bin tm-product-delete-icon"></i>
                                        </button>
                                    @honeypot
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                <hr>
                <!-- table container -->
                <a href="{{ route('coupons.create') }}" class="btn btn-primary btn-block text-uppercase mb-3">
                    {{ __('Add') }}
                </a>
            </div>
        </div>
        @endif

    </div>
@endsection

resources/views/payments/show.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title text-center">{{ __('See Payment Info') }}</h2>
                <table class="table tm-table-small tm-product-table">
                    <tbody>
                        <tr>
                            <td class="tm-product-name">ID</td>
                            <td>{{ $payment->id }}</td>
                        </tr>
                        @if($payment->item_list != null)
                            @foreach( json_decode($payment->item_list) as $item)
                                @foreach($item as $key => $value)
                                <tr>
                                    <td class="tm-product-name">{{ __('Item') }}&nbsp;#{{ $loop->parent->iteration }}</td>
                                    <td>{{ ucfirst($key) }}: {{ $value }}</td>
                                </tr>
                                @endforeach
                            @endforeach
                        @else
                        <tr>
                            <td class="tm-product-name">{{ __('Description') }}</td>
                            <td>{{ $payment->description }}</td>
                        </tr>
                        @endif
                        @if( $currentUser->isMerchantInPayment($payment) )
                            @if($payment->user != null)
                            <tr>
                                <td class="tm-product-name">{{ __('Personal Clients') }}</td>
                                <td>{{ $payment->user->username }}</td>
                            </tr>
                            @endif
                            @if($payment->isMarketplaceInvolved())
                            <tr>
                                <td class="tm-product-name">{{ __('Marketplace') }}</td>
                                <td>{{ $payment->marketplace->user->username }}</td>
                            </tr>
                            @endif
                        @endif

                        @if( $currentUser->isClientInPayment($payment) )
                        <tr>
                            <td class="tm-product-name">{{ __('Merchant') }}</td>
                            <td>{{ $payment->merchant->user->username }}</td>
                        </tr>
                        @endif
                        <tr>
                            <td class="tm-product-name">{{ __('Amount') }}</td>
                            <td>${{ $payment->amount_usd }} + (shipping ${{ $payment->shipping_usd }})</td>
                        </tr>
                        @if($payment->coupon != null)
                        <tr>
                            <td class="tm-product-name">{{ __('Applied Discount') }}</td>
                            <td>-{{ $payment->coupon->discount }}%</td>
                        </tr>
                        @endif
                        <tr>
                            <td class="tm-product-name">{{ __('Status') }}</td>
                            <td>{{ strtoupper($payment->status) }}</td>
                        </tr>
                        @if( $payment->isPending() )
                        <tr>
                            <td class="tm-product-name">URL</td>
                            <td><a href="{{ $payment->url }}" target="_blank" title="payment url" style="color: white">{{ $payment->url }}</a></td>
                        </tr>
                        @endif
                    </tbody>
                </table>
                @if( $currentUser->isMerchantInPayment($payment) && $payment->notes != '' )
                <br><hr>
                <div>
                    <h2 class="tm-block-title">{{ __('Notes') }}</h2>
                    <div class="table tm-table-small tm-product-table">
                    {{ $payment->notes }}
                    </div>
                </div>
                @endif
                @if($currentUser->isMerchantInPayment($payment) && $payment->merchant_id == $currentUser->merchant->id)
                    @if($payment->isCancelled() || $payment->isExpired())
                        <form action="{{ route('payments.destroy', $payment->id) }}" method="POST" class="form-group mt-4">
                        @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-danger btn-block text-uppercase">{{ __('Delete') }}</button>
                        @honeypot
                        </form>
                    @elseif($payment->isPending())
                    <form action="{{ route('payments.cancel', $payment->id) }}" method="POST" class="form-group mt-4">
                        @csrf
                            <button type="submit" class="btn btn-danger btn-block text-uppercase">{{ __('Cancel') }}</button>
                    @honeypot
                    </form>
                    @endif
                @endif
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection