routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Auth')->middleware(['throttle:20,1'])->group(function () {
    // Banned routes...
    Route::get('ban', 'LoginController@ban')->name('ban');
    // Authentication routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('2fa/form', 'LoginController@show_form_2fa')->name('2fa.form');
    Route::post('2fa/challenge', 'LoginController@challenge_2fa')->name('2fa.challenge');
    Route::post('2fa/login', 'LoginController@login_2fa')->name('2fa.login');
    // Registration routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('register-optional', 'RegisterOptionalController@showForm')->name('register.optional');
    Route::post('register-optional', 'RegisterOptionalController@postForm')->name('register.finalize');
    // Password reset routes...
    Route::get('password/recover', 'PasswordController@showPasswordRecoverForm')->name('password.recover');
    Route::post('password/recover', 'PasswordController@checkUserCredentials');
    Route::get('password/reset/{token}', 'PasswordController@showPasswordResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/change', 'PasswordController@showPasswordChangeForm')->name('password.change');
    Route::post('password/change', 'PasswordController@changePswd');
});

Route::middleware(['throttle:60,1'])->group(function () {
    // public routes
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('intro', 'HomeController@intro')->name('intro');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('contacts', 'HomeController@contacts')->name('contacts');
    Route::post('contacts', 'HomeController@sendMessage')->name('send_msg');
    Route::get('menu', 'HomeController@menu')->name('menu');
    Route::get('api', 'HomeController@api')->name('api');

    // user private routes
    Route::get('home', 'PrivateController@home')->name('home');
    Route::post('changetier', 'UserTierController@generateDepositAddress')->name('changetier');
    Route::post('wallet', 'PrivateController@setRefundWallet')->name('setwallet');
    Route::post('setlanguage', 'PrivateController@setLanguage')->name('setlanguage');
    Route::post('actas', 'PrivateController@actingAsUser')->name('set_actas');
    Route::get('markasread/{id}', 'PrivateController@markAsRead')->name('markasread');
    Route::post('addpgp', 'PrivateController@addPgpKey')->name('addpgp');
    Route::get('removepgp', 'PrivateController@removePgpKey')->name('removepgp');
    Route::get('enable2fa', 'PrivateController@enable2fa')->name('enable_2fa');
    Route::get('disable2fa', 'PrivateController@disable2fa')->name('disable_2fa');

    // tokens
    Route::get('tokens', 'TokenController@index')->name('tokens.index');
    Route::delete('tokens/{token}', 'TokenController@destroy')->name('tokens.delete');
    Route::get('tokens/revoke/{token}', 'TokenController@revoke')->name('tokens.revoke');

    // cancel payments
    Route::post('/payments/cancel/{payment}', 'PaymentRequestController@cancel')->name('payments.cancel');

    // resource controllers
    Route::resource('users', 'UserController');
    Route::resource('payments', 'PaymentRequestController');
    Route::resource('disputes', 'DisputeController');
    Route::resource('coupons', 'CouponController');
    Route::resource('tickets', 'TicketController');
    Route::resource('merchants', 'MerchantController');
    Route::resource('marketplaces', 'MarketplaceController');

    // merchant wallet
    Route::post('merchants/wallet', 'MerchantController@setPersonalWallet')->name('merchant.setwallet');

    // marketplace wallet
    Route::post('marketplaces/wallet', 'MarketplaceController@setWallet')->name('marketplace.setwallet');

    // checkout process
    Route::prefix('checkout')->group(function () {
        Route::get('/review/{payment}', 'CheckoutController@review')->name('checkout.review');
        Route::get('/wallet/{payment}', 'CheckoutController@wallet')->name('checkout.wallet');
        Route::get('/currency/{payment}', 'CheckoutController@currency')->name('checkout.currency');
        Route::get('/pay/{payment}/{cryptocurrency}', 'CheckoutController@pay')->name('checkout.pay');
        Route::get('/verify/{payment}', 'CheckoutController@verify')->name('checkout.verify');
        Route::post('/coupon', 'CheckoutController@coupon')->name('checkout.coupon');
        Route::get('/success', 'CheckoutController@successPage')->name('checkout.success');
        Route::get('/cancel', 'CheckoutController@cancelPage')->name('checkout.cancel');
        Route::get('/expired', 'CheckoutController@expiredPage')->name('checkout.expired');
    });

    Route::namespace('Admin')->middleware(['staff'])->prefix('admin')->group(function () {
        Route::get('/online', 'AdminController@online')->name('admin.online');
        Route::get('/offline', 'AdminController@offline')->name('admin.offline');
        Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
        Route::get('/interactions', 'AdminController@interactions')->name('admin.interactions');
        Route::get('/messages', 'AdminController@messages')->name('admin.messages');
        Route::get('/logs', 'LogsController@index')->name('admin.logs');
        Route::get('/logs/clear', 'LogsController@clear')->name('admin.clearlogs');

        // news
        Route::get('/news', 'AdminNewsController@index')->name('admin.news.index');
        Route::get('/news/create', 'AdminNewsController@create')->name('admin.news.create');
        Route::post('/news', 'AdminNewsController@store')->name('admin.news.store');
        Route::delete('/news/{news}', 'AdminNewsController@destroy')->name('admin.news.destroy');
        // users
        Route::get('/users', 'AdminUserController@index')->name('admin.users.index');
        Route::get('/users/show/{user}', 'AdminUserController@show')->name('admin.users.show');
        Route::get('/users/removed', 'AdminUserController@removed')->name('admin.users.removed');
        Route::get('/users/restore/{id}', 'AdminUserController@restore')->name('admin.users.restore');
        Route::get('/users/merchant/{user}', 'AdminUserController@makeMerchant')->name('admin.users.makemerchant');
        Route::get('/users/marketplace/{user}', 'AdminUserController@makeMarketplace')->name('admin.users.makemarketplace');
        Route::get('/ban/{user}', 'AdminUserController@ban')->name('admin.users.ban');
        Route::get('/unban/{user}', 'AdminUserController@unban')->name('admin.users.unban');
        // disputes
        Route::get('/disputes', 'AdminDisputeController@index')->name('admin.disputes.index');
        Route::get('/disputes/review', 'AdminDisputeController@review')->name('admin.disputes.review');
        Route::get('/disputes/show/{dispute}', 'AdminDisputeController@show')->name('admin.disputes.show');
        Route::get('/disputes/accept/{dispute}', 'AdminDisputeController@accept')->name('admin.disputes.accept');
        Route::get('/disputes/reject/{dispute}', 'AdminDisputeController@reject')->name('admin.disputes.reject');
        // payments
        Route::get('/payments', 'AdminPaymentController@index')->name('admin.payments.index');
        Route::get('/payments/reported', 'AdminPaymentController@reported')->name('admin.payments.reported');
        Route::get('/payments/show/{payment}', 'AdminPaymentController@show')->name('admin.payments.show');
        // tickets
        Route::get('/tickets', 'AdminTicketController@index')->name('admin.tickets.index');
        Route::get('/tickets/open', 'AdminTicketController@open')->name('admin.tickets.open');
        Route::get('/tickets/show/{ticket}', 'AdminTicketController@show')->name('admin.tickets.show');
        Route::get('/tickets/change/status/{ticket}/{status}', 'AdminTicketController@changeStatus')->name('admin.tickets.changestatus');
        Route::get('/tickets/change/priority/{ticket}/{priority}', 'AdminTicketController@changePriority')->name('admin.tickets.changepriority');
        // cryptocurrencies
        Route::get('/cryptocurrencies', 'AdminCryptocurrencyController@index')->name('admin.cryptocurrencies.index');
        Route::get('/cryptocurrencies/create', 'AdminCryptocurrencyController@create')->name('admin.cryptocurrencies.create');
        Route::post('/cryptocurrencies', 'AdminCryptocurrencyController@store')->name('admin.cryptocurrencies.store');
        Route::get('/cryptocurrencies/edit/{cryptocurrency}', 'AdminCryptocurrencyController@edit')->name('admin.cryptocurrencies.edit');
        Route::post('/cryptocurrencies/update/{cryptocurrency}', 'AdminCryptocurrencyController@update')->name('admin.cryptocurrencies.update');
        Route::delete('/cryptocurrencies/{cryptocurrency}', 'AdminCryptocurrencyController@destroy')->name('admin.cryptocurrencies.destroy');

        //Route::diskMonitor('/disks');
    });

    // oauth passport
    Route::prefix('oauth')->middleware(['merchant'])->group(function () {
        Route::get('/authorize', '\Laravel\Passport\Http\Controllers\AuthorizationController@authorize')->name('passport.authorizations.authorize');
        Route::post('/authorize', 'OauthController@approve')->name('passport.authorizations.approve');
        Route::delete('/authorize', '\Laravel\Passport\Http\Controllers\DenyAuthorizationController@deny')->name('passport.authorizations.deny');
    });

});

// autodestruction

app/Models/States/Ticket/Closed.php
<?php

namespace App\Models\States\Ticket;

class Closed extends TicketState
{
    public static $name = 'closed';

    public function text(): string
    {
        return 'closed';
    }
}

app/Models/States/Ticket/Open.php
<?php

namespace App\Models\States\Ticket;

class Open extends TicketState
{
    public static $name = 'open';

    public function text(): string
    {
        return 'open';
    }
}

app/Models/States/Ticket/TicketState.php
<?php

namespace App\Models\States\Ticket;

use Spatie\ModelStates\State;

abstract class TicketState extends State
{
    abstract public function text(): string;
}

app/Models/Ticket.php
<?php

namespace App\Models;

use App\Enums\Priority;
use App\Models\States\Ticket\Closed;
use App\Models\States\Ticket\Open;
use App\Models\States\Ticket\TicketState;
use BenSampo\Enum\Traits\CastsEnums;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use RichardStyles\EloquentEncryption\Casts\Encrypted;
use Spatie\ModelCleanup\CleanupConfig;
use Spatie\ModelCleanup\GetsCleanedUp;
use Spatie\ModelStates\HasStates;

class Ticket extends Model implements GetsCleanedUp
{
    use HasStates, CastsEnums, Cachable, HasFactory;

    protected $fillable = [
        'user_id',
        'ticket_category_id',
        'title',
        'priority',
        'message',
        'status',
    ];

    protected $casts = [
        'user_id'               => 'integer',
        'ticket_category_id'    => 'integer',
        'created_at'            => 'datetime',
        'updated_at'            => 'datetime',
        'priority'              => Priority::class,
        'message'               => Encrypted::class,
    ];

    /**
     * Scopes.
     */
    public function scopeOpen($query)
    {
        return $query->whereState('status', Open::class);
    }

    public function scopeClosed($query)
    {
        return $query->whereState('status', Closed::class);
    }

    public function scopeLowPriority($query)
    {
        return $query->where('priority', Priority::LOW);
    }

    public function scopeMediumPriority($query)
    {
        return $query->where('priority', Priority::MEDIUM);
    }

    public function scopeHighPriority($query)
    {
        return $query->where('priority', Priority::HIGH);
    }

    /**
     * Identities.
     */
    public function isOpen(): bool
    {
        return $this->status == 'open';
    }

    public function isClosed(): bool
    {
        return $this->status == 'closed';
    }

    public function isLowPriority()
    {
        $priority = Priority::getInstance($this->priority);

        return $priority->is(Priority::LOW);
    }

    public function isMediumPriority()
    {
        $priority = Priority::getInstance($this->priority);

        return $priority->is(Priority::MEDIUM);
    }

    public function isHighPriority()
    {
        $priority = Priority::getInstance($this->priority);

        return $priority->is(Priority::HIGH);
    }

    /**
     * States.
     */
    protected function registerStates(): void
    {
        $this
            ->addState('status', TicketState::class)
            ->default(Open::class)
            ->allowTransition(Open::class, Closed::class);
    }

    /**
     * Clean-up.
     */
    public function cleanUp(CleanupConfig $config): void
    {
        $config->useDateAttribute('updated_at')->olderThanDays(30);
    }

    /**
     * Eloquent Relationships.
     */
    public function ticketComments(): HasMany
    {
        return $this->hasMany(TicketComment::class);
    }

    public function ticketCategory(): BelongsTo
    {
        return $this->belongsTo(TicketCategory::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTicket;
use App\Http\Requests\UpdateTicket;
use App\Models\States\Ticket\Open;
use App\Models\Ticket;
use App\Models\TicketCategory;
use App\Models\TicketComment;
use Illuminate\Support\Facades\Auth;

class TicketController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Ticket::class, 'ticket');
        $this->middleware('auth');
    }

    /**
     * @brief Displays a listing of the ticket.
     */
    public function index()
    {
        $tickets = Ticket::where('user_id', Auth::user()->id)->get();
        $open_tickets = Ticket::where('user_id', Auth::user()->id)->open()->latest()->limit(3)->get();
        $closed_tickets = Ticket::where('user_id', Auth::user()->id)->closed()->latest()->limit(3)->get();

        return view('tickets.index', compact('tickets', 'open_tickets', 'closed_tickets'));
    }

    /**
     * @brief Shows the form for opening a new ticket.
     */
    public function create()
    {
        $categories = TicketCategory::all();

        return view('tickets.create', compact('categories'));
    }

    /**
     * @brief Stores a newly created ticket in storage.
     */
    public function store(CreateTicket $request)
    {
        $user = Auth::user();

        $ticket = Ticket::firstOrCreate([
            'user_id' => $user->id,
            'ticket_category_id' => $request->ticket_category_id,
            'title' => $request->title,
            'message' => $request->message,
        ]);

        activity()
        ->performedOn($ticket)
        ->causedBy($user)
        ->log('new ticket created');

        return redirect()->route('tickets.index')->with('message', __('Ticket successfully created.'));
    }

    /**
     * @brief Displays the specified ticket.
     */
    public function show(Ticket $ticket)
    {
        return view('tickets.show', compact('ticket'));
    }

    /**
     * @brief Updates the specified ticket in storage adding a new user comment.
     */
    public function update(UpdateTicket $request, Ticket $ticket)
    {
        if ($ticket->isClosed()) {
            $ticket->transitionTo(Open::class);
        } else {
            $ticket->touch();
        }

        $user = Auth::user();

        TicketComment::firstOrCreate([
            'comment' => $request->comment,
            'ticket_id' => $request->ticket_id,
            'user_id' => $user->id,
        ]);

        activity()
        ->performedOn($ticket)
        ->causedBy($user)
        ->log('added comment to ticket');

        // check if it is a staff member replying
        if ($ticket->user_id != $user->id) {
            return redirect()->route('admin.tickets.show', ['ticket' => $ticket])->with('message', __('Your reply has been saved.'));
        }

        return redirect()->route('tickets.index')->with('message', __('Your reply has been saved.'));
    }

    /**
     * @brief Removes the specified ticket from storage.
     */
    public function destroy(Ticket $ticket)
    {
        $ticket->delete();

        return redirect()->route('tickets.index')->with('message', __('Ticket successfully deleted.'));
    }
}

resources/views/tickets/create.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Open a Ticket') }}</h2>
                <form method="POST" action="{{ route('tickets.store') }}" class="tm-login-form">
                @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input id="title" name="title" type="text" class="form-control validate @error('title') is-invalid @enderror" placeholder="{{ __('Sum up your problem in a few words') }}" value="{{ old('title') }}"  minlength="3" maxlength="190" required autofocus>
                        @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="ticket_category_id">{{ __('Category') }}</label>
                        <select id="ticket_category_id" name="ticket_category_id" class="custom-select validate @error('ticket_category_id') is-invalid @enderror" required>
                            <option>{{ __('Choose') }}...</option>
                            @foreach($categories as $category)
                            <option value="{{ $category->id }}"
                            @if(old('ticket_category_id') == $category->id)
                            selected
                            @endif
                            >{{ $category->name }}</option>
                            @endforeach
                        </select>
                        @error('ticket_category_id')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="message">{{ __('Message') }}</label>
                        <textarea id="message" name="message" class="form-control validate @error('message') is-invalid @enderror" placeholder="{{ __('Describe in detail what went wrong') }}" minlength="10" maxlength="5000" required>{{ old('message') }}</textarea>
                        @error('message')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Create') }}</button>
                    </div>
                @honeypot
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection

resources/views/tickets/index.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block">
                <h2 class="tm-block-title">{{ __('Open') }}</h2>
                <table class="table tm-table-small tm-product-table">
                    <tbody>
                        @foreach($open_tickets as $ticket)
                        <tr>
                            <td class="tm-product-name">{{ $ticket->title }}</td>
                            <td class="text-center">
                            <a href="{{ route('tickets.show', $ticket) }}" class="tm-product-delete-link">
                                <i class="icss-arrow-right tm-product-delete-icon"></i>
                            </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block">
                <h2 class="tm-block-title">{{ __('Closed') }}</h2>
                <table class="table tm-table-small tm-product-table">
                    <tbody>
                        @foreach($closed_tickets as $ticket)
                        <tr>
                            <td class="tm-product-name">{{ $ticket->title }}</td>
                            <td class="text-center">
                            <a href="{{ route('tickets.show', $ticket) }}" class="tm-product-delete-link">
                                <i class="icss-arrow-right tm-product-delete-icon"></i>
                            </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Tickets List') }}</h2>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">{{ __('TITLE') }}</th>
                            <th scope="col">{{ __('CATEGORY') }}</th>
                            <th scope="col">{{ __('STATUS') }}</th>
                            <th scope="col">{{ __('DATE') }}</th>
                            <th scope="col">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tickets as $ticket)
                        <tr>
                            <td scope="row"><b><a style="color: white" href="{{ route('tickets.show', $ticket->id) }}">{{ $ticket->title }}</a></b></td>
                            <td>{{ $ticket->ticketCategory->name }}</td>
                            <td>
                                @if($ticket->isOpen())
                                <div class="tm-status-circle moving">
                                </div>{{ __('Open') }}
                                @else
                                <div class="tm-status-circle cancelled">
                                </div>{{ __('Closed') }}
                                @endif
                            </td>
                            <td>{{ $ticket->created_at->format('m/d/Y') }}</td>
                            <td>
                                <form action="{{ route('tickets.destroy', $ticket) }}" method="POST">
                                @csrf
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <button class="tm-product-delete-link" type="submit">
                                        <i class="icss-bin tm-product-delete-icon"></i>
                                    </button>
                                @honeypot
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <hr>
                <a href="{{ route('tickets.create') }}" class="btn btn-primary btn-block text-uppercase mb-3" title="{{ __('Open a ticket') }}">{{ __('Open a ticket') }}</a>
            </div>
        </div>
    </div>
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
    <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">{{ __('View a Ticket') }}</h2>
                    <table class="table tm-table-small tm-product-table">
                        <tbody>
                            <tr>
                                <td class="tm-product-name">{{ __('Ticket ID') }}</td>
                                <td>{{ $ticket->id }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Title') }}</td>
                                <td>{{ $ticket->title }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Category') }}</td>
                                <td>{{ $ticket->ticketCategory->name }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Message') }}</td>
                                <td>{{ $ticket->message }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Priority') }}</td>
                                <td>{{ $ticket->priority->key }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Status') }}</td>
                                <td>{{ strtoupper($ticket->status) }}</td>
                            </tr>
                            @foreach($ticket->ticketComments as $comment)
                            <tr>
                                <td class="tm-product-name">{{ $comment->user->username }} {{ __('commented') }}</td>
                                <td>{{ $comment->comment }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Add Comment') }}</h2>
                <form method="POST" action="{{ route('tickets.update', $ticket) }}" class="tm-login-form">
                @csrf
                    <input type="hidden" name="_method" value="PUT">
                    <input id="ticket_id" name="ticket_id" value="{{ $ticket->id }}" type="hidden">
                    <textarea id="comment" name="comment" class="form-control validate @error('comment') is-invalid @enderror"
                     required>{{ old('comment') }}</textarea>
                    @error('comment')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <div class="form-group mt-4">
                    @if($ticket->isClosed())
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Reopen Ticket') }}</button>
                    @else
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Reply') }}</button>
                    @endif
                    </div>
                @honeypot
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection