routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Auth')->middleware(['throttle:20,1'])->group(function () {
    // Banned routes...
    Route::get('ban', 'LoginController@ban')->name('ban');
    // Authentication routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('2fa/form', 'LoginController@show_form_2fa')->name('2fa.form');
    Route::post('2fa/challenge', 'LoginController@challenge_2fa')->name('2fa.challenge');
    Route::post('2fa/login', 'LoginController@login_2fa')->name('2fa.login');
    // Registration routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('register-optional', 'RegisterOptionalController@showForm')->name('register.optional');
    Route::post('register-optional', 'RegisterOptionalController@postForm')->name('register.finalize');
    // Password reset routes...
    Route::get('password/recover', 'PasswordController@showPasswordRecoverForm')->name('password.recover');
    Route::post('password/recover', 'PasswordController@checkUserCredentials');
    Route::get('password/reset/{token}', 'PasswordController@showPasswordResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');
    Route::get('password/change', 'PasswordController@showPasswordChangeForm')->name('password.change');
    Route::post('password/change', 'PasswordController@changePswd');
});

Route::middleware(['throttle:60,1'])->group(function () {
    // public routes
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('intro', 'HomeController@intro')->name('intro');
    Route::get('about', 'HomeController@about')->name('about');
    Route::get('contacts', 'HomeController@contacts')->name('contacts');
    Route::post('contacts', 'HomeController@sendMessage')->name('send_msg');
    Route::get('menu', 'HomeController@menu')->name('menu');
    Route::get('api', 'HomeController@api')->name('api');

    // user private routes
    Route::get('home', 'PrivateController@home')->name('home');
    Route::post('changetier', 'UserTierController@generateDepositAddress')->name('changetier');
    Route::post('wallet', 'PrivateController@setRefundWallet')->name('setwallet');
    Route::post('setlanguage', 'PrivateController@setLanguage')->name('setlanguage');
    Route::post('actas', 'PrivateController@actingAsUser')->name('set_actas');
    Route::get('markasread/{id}', 'PrivateController@markAsRead')->name('markasread');
    Route::post('addpgp', 'PrivateController@addPgpKey')->name('addpgp');
    Route::get('removepgp', 'PrivateController@removePgpKey')->name('removepgp');
    Route::get('enable2fa', 'PrivateController@enable2fa')->name('enable_2fa');
    Route::get('disable2fa', 'PrivateController@disable2fa')->name('disable_2fa');

    // tokens
    Route::get('tokens', 'TokenController@index')->name('tokens.index');
    Route::delete('tokens/{token}', 'TokenController@destroy')->name('tokens.delete');
    Route::get('tokens/revoke/{token}', 'TokenController@revoke')->name('tokens.revoke');

    // cancel payments
    Route::post('/payments/cancel/{payment}', 'PaymentRequestController@cancel')->name('payments.cancel');

    // resource controllers
    Route::resource('users', 'UserController');
    Route::resource('payments', 'PaymentRequestController');
    Route::resource('disputes', 'DisputeController');
    Route::resource('coupons', 'CouponController');
    Route::resource('tickets', 'TicketController');
    Route::resource('merchants', 'MerchantController');
    Route::resource('marketplaces', 'MarketplaceController');

    // merchant wallet
    Route::post('merchants/wallet', 'MerchantController@setPersonalWallet')->name('merchant.setwallet');

    // marketplace wallet
    Route::post('marketplaces/wallet', 'MarketplaceController@setWallet')->name('marketplace.setwallet');

    // checkout process
    Route::prefix('checkout')->group(function () {
        Route::get('/review/{payment}', 'CheckoutController@review')->name('checkout.review');
        Route::get('/wallet/{payment}', 'CheckoutController@wallet')->name('checkout.wallet');
        Route::get('/currency/{payment}', 'CheckoutController@currency')->name('checkout.currency');
        Route::get('/pay/{payment}/{cryptocurrency}', 'CheckoutController@pay')->name('checkout.pay');
        Route::get('/verify/{payment}', 'CheckoutController@verify')->name('checkout.verify');
        Route::post('/coupon', 'CheckoutController@coupon')->name('checkout.coupon');
        Route::get('/success', 'CheckoutController@successPage')->name('checkout.success');
        Route::get('/cancel', 'CheckoutController@cancelPage')->name('checkout.cancel');
        Route::get('/expired', 'CheckoutController@expiredPage')->name('checkout.expired');
    });

    Route::namespace('Admin')->middleware(['staff'])->prefix('admin')->group(function () {
        Route::get('/online', 'AdminController@online')->name('admin.online');
        Route::get('/offline', 'AdminController@offline')->name('admin.offline');
        Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
        Route::get('/interactions', 'AdminController@interactions')->name('admin.interactions');
        Route::get('/messages', 'AdminController@messages')->name('admin.messages');
        Route::get('/logs', 'LogsController@index')->name('admin.logs');
        Route::get('/logs/clear', 'LogsController@clear')->name('admin.clearlogs');

        // news
        Route::get('/news', 'AdminNewsController@index')->name('admin.news.index');
        Route::get('/news/create', 'AdminNewsController@create')->name('admin.news.create');
        Route::post('/news', 'AdminNewsController@store')->name('admin.news.store');
        Route::delete('/news/{news}', 'AdminNewsController@destroy')->name('admin.news.destroy');
        // users
        Route::get('/users', 'AdminUserController@index')->name('admin.users.index');
        Route::get('/users/show/{user}', 'AdminUserController@show')->name('admin.users.show');
        Route::get('/users/removed', 'AdminUserController@removed')->name('admin.users.removed');
        Route::get('/users/restore/{id}', 'AdminUserController@restore')->name('admin.users.restore');
        Route::get('/users/merchant/{user}', 'AdminUserController@makeMerchant')->name('admin.users.makemerchant');
        Route::get('/users/marketplace/{user}', 'AdminUserController@makeMarketplace')->name('admin.users.makemarketplace');
        Route::get('/ban/{user}', 'AdminUserController@ban')->name('admin.users.ban');
        Route::get('/unban/{user}', 'AdminUserController@unban')->name('admin.users.unban');
        // disputes
        Route::get('/disputes', 'AdminDisputeController@index')->name('admin.disputes.index');
        Route::get('/disputes/review', 'AdminDisputeController@review')->name('admin.disputes.review');
        Route::get('/disputes/show/{dispute}', 'AdminDisputeController@show')->name('admin.disputes.show');
        Route::get('/disputes/accept/{dispute}', 'AdminDisputeController@accept')->name('admin.disputes.accept');
        Route::get('/disputes/reject/{dispute}', 'AdminDisputeController@reject')->name('admin.disputes.reject');
        // payments
        Route::get('/payments', 'AdminPaymentController@index')->name('admin.payments.index');
        Route::get('/payments/reported', 'AdminPaymentController@reported')->name('admin.payments.reported');
        Route::get('/payments/show/{payment}', 'AdminPaymentController@show')->name('admin.payments.show');
        // tickets
        Route::get('/tickets', 'AdminTicketController@index')->name('admin.tickets.index');
        Route::get('/tickets/open', 'AdminTicketController@open')->name('admin.tickets.open');
        Route::get('/tickets/show/{ticket}', 'AdminTicketController@show')->name('admin.tickets.show');
        Route::get('/tickets/change/status/{ticket}/{status}', 'AdminTicketController@changeStatus')->name('admin.tickets.changestatus');
        Route::get('/tickets/change/priority/{ticket}/{priority}', 'AdminTicketController@changePriority')->name('admin.tickets.changepriority');
        // cryptocurrencies
        Route::get('/cryptocurrencies', 'AdminCryptocurrencyController@index')->name('admin.cryptocurrencies.index');
        Route::get('/cryptocurrencies/create', 'AdminCryptocurrencyController@create')->name('admin.cryptocurrencies.create');
        Route::post('/cryptocurrencies', 'AdminCryptocurrencyController@store')->name('admin.cryptocurrencies.store');
        Route::get('/cryptocurrencies/edit/{cryptocurrency}', 'AdminCryptocurrencyController@edit')->name('admin.cryptocurrencies.edit');
        Route::post('/cryptocurrencies/update/{cryptocurrency}', 'AdminCryptocurrencyController@update')->name('admin.cryptocurrencies.update');
        Route::delete('/cryptocurrencies/{cryptocurrency}', 'AdminCryptocurrencyController@destroy')->name('admin.cryptocurrencies.destroy');

        //Route::diskMonitor('/disks');
    });

    // oauth passport
    Route::prefix('oauth')->middleware(['merchant'])->group(function () {
        Route::get('/authorize', '\Laravel\Passport\Http\Controllers\AuthorizationController@authorize')->name('passport.authorizations.authorize');
        Route::post('/authorize', 'OauthController@approve')->name('passport.authorizations.approve');
        Route::delete('/authorize', '\Laravel\Passport\Http\Controllers\DenyAuthorizationController@deny')->name('passport.authorizations.deny');
    });

});

// autodestruction

app/Models/Dispute.php
<?php

namespace App\Models;

use App\Models\States\Dispute\Accepted;
use App\Models\States\Dispute\DisputeState;
use App\Models\States\Dispute\InReview;
use App\Models\States\Dispute\Open;
use App\Models\States\Dispute\Rejected;
use GeneaLabs\LaravelModelCaching\Traits\Cachable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use RichardStyles\EloquentEncryption\Casts\Encrypted;
use Spatie\ModelStates\HasStates;

class Dispute extends Model
{
    use HasStates, HasFactory, Cachable;

    public $incrementing = false;

    protected $fillable = [
        'payment_request_id',
        'user_notes',
        'merchant_notes',
        'status',
    ];

    protected $casts = [
        'user_notes'            => Encrypted::class,
        'merchant_notes'        => Encrypted::class,
        'created_at'            => 'datetime',
        'updated_at'            => 'datetime',
    ];

    /**
     * Scopes.
     */
    public function scopeOpen($query)
    {
        return $query->whereState('status', Open::class);
    }

    public function scopeAccepted($query)
    {
        return $query->whereState('status', Accepted::class);
    }

    public function scopeRejected($query)
    {
        return $query->whereState('status', Rejected::class);
    }

    public function scopeInReview($query)
    {
        return $query->whereState('status', InReview::class);
    }

    /**
     * Identities.
     */
    public function isOpen(): bool
    {
        return $this->status == 'open';
    }

    public function isAccepted(): bool
    {
        return $this->status == 'accepted';
    }

    public function isRejected(): bool
    {
        return $this->status == 'rejected';
    }

    public function isInReview(): bool
    {
        return $this->status == 'in_review';
    }

    /**
     * States.
     */
    protected function registerStates(): void
    {
        $this
            ->addState('status', DisputeState::class)
            ->default(Open::class)
            ->allowTransition(Open::class, InReview::class)
            ->allowTransition(InReview::class, Accepted::class)
            ->allowTransition(InReview::class, Rejected::class);
    }

    /**
     * Eloquent Relationships.
     */
    public function paymentRequest(): BelongsTo
    {
        return $this->belongsTo(PaymentRequest::class);
    }

    /**
     * Custom primary key.
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->{$model->getKeyName()} = hexdec(uniqid());
        });
    }
}

app/Models/States/Dispute/Accepted.php
<?php

namespace App\Models\States\Dispute;

class Accepted extends DisputeState
{
    public static $name = 'accepted';

    public function text(): string
    {
        return 'accepted';
    }
}

app/Http/Controllers/DisputeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateDispute;
use App\Http\Requests\EditDispute;
use App\Models\Dispute;
use App\Models\PaymentRequest;
use App\Models\States\Dispute\InReview;
use App\Models\States\PaymentRequest\Funded;
use App\Models\States\PaymentRequest\Reported;
use App\Notifications\DisputeOpened;
use App\Notifications\DisputeUpdated;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DisputeController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Dispute::class, 'dispute');
        $this->middleware('auth');
    }

    /**
     * @brief Shows all disputes, latest 3 refunds
     *        and latest 3 open disputes
     */
    public function index()
    {
        $user = Auth::user();

        if ($user->isMerchant()) {
            $disputes = $user->merchant->disputes()->with('paymentRequest')->latest()->get();
            $latest_open = []; /* $user->merchant->disputes()->InReview()->latest()->limit(3)->get(); */
            $refunds = $user->merchant->paymentRequests()->with('dispute')->refunded()->latest()->limit(3)->get();
        } else {
            $disputes = $user->disputes()->with('paymentRequest')->get();
            $latest_open = []; /* $user->disputes()->InReview()->with('paymentRequest')->latest()->limit(3)->get(); */
            $refunds = PaymentRequest::refunded()->where('user_id', $user->id)->with('dispute')->latest()->limit(3)->get();
        }

        return view('disputes.index', compact('disputes', 'latest_open', 'refunds'));
    }

    /**
     * @brief Creates a dispute for a given payment request
     *        only if there is no dispute already registered
     */
    public function create()
    {
        $payment = PaymentRequest::findOrFail(request()->payment_id);

        if ($payment->dispute) {
            return redirect()->route('disputes.index')->withError(__('A dispute for this payment is already opened.'));
        }

        return view('disputes.create', compact('payment'));
    }

    /**
     * @brief Shows merchant reply form
     */
    public function edit(Dispute $dispute)
    {
        $payment = $dispute->paymentRequest;

        return view('disputes.edit', compact('dispute', 'payment'));
    }

    /**
     * @brief Stores a newly created dispute and sends a notification
     *        to the merchant
     */
    public function store(CreateDispute $request)
    {
        $user = Auth::user();
        $payment = PaymentRequest::findOrFail($request->payment_request_id);
        if ($payment->isFE()) {
            return redirect()->route('disputes.index')->withError(__('The finalize early payment method is not moderated.'));
        }

        if ($user->isMerchantInPayment($payment)) {
            return redirect()->route('disputes.index')->withError(__('Only customers can open a dispute'));
        }

        $payment->transitionTo(Reported::class);

        $dispute = Dispute::firstOrCreate([
            'payment_request_id'    => $request->payment_request_id,
            'user_notes'            => $request->user_notes,
        ]);

        $payment->merchant->user->notify(new DisputeOpened($dispute));

        activity()
        ->performedOn($dispute)
        ->causedBy($user)
        ->log('new dispute');

        return redirect()->route('disputes.index')->with('message', __('A new dispute has been opened.'));
    }

    /**
     * @brief Shows a dispute
     */
    public function show(Dispute $dispute)
    {
        return view('disputes.show', compact('dispute'));
    }

    /**
     * @brief Saves merchant reply
     */
    public function update(EditDispute $request, Dispute $dispute)
    {
        if (! $dispute->isOpen()) {
            return redirect()->route('disputes.index')->withError(__('Disputes under review cannot be updated.'));
        }

        $dispute->update(['merchant_notes' => $request->merchant_notes]);
        $dispute->transitionTo(InReview::class);

        $dispute->paymentRequest->user->notify(new DisputeUpdated($dispute));

        activity()
        ->performedOn($dispute)
        ->causedBy(Auth::user())
        ->log('dispute updated');

        return redirect()->route('disputes.index')->with('message', __('Merchant reply was saved.'));
    }

    /**
     * @brief Deletes a dispute
     */
    public function destroy(Dispute $dispute)
    {
        if (! $dispute->isOpen()) {
            return redirect()->route('disputes.index')->withError(__('This dispute cannot be deleted yet.'));
        }

        $dispute->paymentRequest->transitionTo(Funded::class);

        activity()
        ->performedOn($dispute)
        ->causedBy(Auth::user())
        ->log('dispute deleted');

        $dispute->delete();

        return redirect()->route('disputes.index')->with('message', __('The dispute has been deleted.'));
    }
}

resources/views/disputes/create.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Open new dispute') }}</h2>
                    <table class="table tm-table-small tm-product-table">
                        <tbody>
                            <tr>
                                <td class="tm-product-name">{{ __('Payment') }}&nbsp;ID</td>
                                <td>{{ $payment->id }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Merchant') }}</td>
                                <td>{{ $payment->merchant->user->username }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Price') }}</td>
                                <td>${{ $payment->getFinalPrice() }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Payment Status') }}</td>
                                <td>{{ strtoupper($payment->status) }}</td>
                            </tr>
                            @if($payment->coupon != null)
                            <tr>
                                <td class="tm-product-name">{{ __('Discount Applied') }}</td>
                                <td>{{ $payment->coupon->discount }}%</td>
                            </tr>
                            @endif
                            @if($payment->item_list != null)
                                @foreach( json_decode($payment->item_list) as $item)
                                    @foreach($item as $key => $value)
                                    <tr>
                                        <td class="tm-product-name">{{ __('Item') }}&nbsp;#{{ $loop->parent->iteration }}</td>
                                        <td>{{ ucfirst($key) }}: {{ $value }}</td>
                                    </tr>
                                    @endforeach
                                @endforeach
                            @endif
                        </tbody>
                    </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('User’s Notes') }}</h2>
                <form method="POST" action="{{ route('disputes.store') }}" class="tm-login-form">
                @csrf
                    <input name="payment_request_id" value="{{ $payment->id }}" type="hidden">
                    <textarea id="user_notes" name="user_notes" class="form-control validate @error('user_notes') is-invalid @enderror" placeholder="{{ __('Describe in detail what went wrong and why you should be reimbursed') }}" minlength="10" maxlength="5000" required autofocus>{{ old('user_notes') }}</textarea>
                    @error('user_notes')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Open') }}</button>
                    </div>
                @honeypot
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Merchant Notes') }}</h2>
                <textarea class="form-control" disabled></textarea>
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection

resources/views/disputes/edit.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Open new dispute') }}</h2>
                    <table class="table tm-table-small tm-product-table">
                        <tbody>
                            <tr>
                                <td class="tm-product-name">{{ __('Payment') }}&nbsp;ID</td>
                                <td>{{ $payment->id }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Merchant') }}</td>
                                <td>{{ $payment->merchant->user->username }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Price') }}</td>
                                <td>${{ $payment->getFinalPrice() }}</td>
                            </tr>
                            <tr>
                                <td class="tm-product-name">{{ __('Payment Status') }}</td>
                                <td>{{ strtoupper($payment->status) }}</td>
                            </tr>
                            @if($payment->coupon != null)
                            <tr>
                                <td class="tm-product-name">{{ __('Discount Applied') }}</td>
                                <td>{{ $payment->coupon->discount }}%</td>
                            </tr>
                            @endif
                            @if($payment->item_list != null)
                                @foreach( json_decode($payment->item_list) as $item)
                                    @foreach($item as $key => $value)
                                    <tr>
                                        <td class="tm-product-name">{{ __('Item') }}&nbsp;#{{ $loop->parent->iteration }}</td>
                                        <td>{{ ucfirst($key) }}: {{ $value }}</td>
                                    </tr>
                                    @endforeach
                                @endforeach
                            @endif
                        </tbody>
                    </table>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('User’s Notes') }}</h2>
                <textarea class="form-control" disabled>{{ $dispute->user_notes }}</textarea>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Merchant Notes') }}</h2>
                <form method="POST" action="{{ route('disputes.update', $dispute) }}" class="tm-login-form">
                @csrf

                @method('PUT')
                    <textarea id="merchant_notes" name="merchant_notes" class="form-control validate @error('merchant_notes') is-invalid @enderror" placeholder="{{ __('Describe in detail what went wrong') }}" minlength="10" maxlength="5000" required autofocus>{{ old('merchant_notes') }}</textarea>
                    @error('merchant_notes')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-primary btn-block text-uppercase">{{ __('Reply') }}</button>
                    </div>
                @honeypot
                </form>
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection

resources/views/disputes/show.blade.php
@extends('layouts.private')

@section('content')
    <!-- row -->
    <div class="row tm-content-row">
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('User’s Notes') }}</h2>
                <div class="table tm-table-small tm-product-table">
                {{ $dispute->user_notes }}
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('Merchant Notes') }}</h2>
                <div class="table tm-table-small tm-product-table">
                {{ $dispute->merchant_notes }}
                </div>
            </div>
        </div>
        <div class="col-12 tm-block-col">
            <div class="tm-bg-primary-dark tm-block tm-block-scroll">
                <h2 class="tm-block-title">{{ __('See Payment Info') }}</h2>
                <table class="table tm-table-small tm-product-table">
                    <tbody>
                        <tr>
                            <td class="tm-product-name">{{ __('Payment') }}&nbsp;ID</td>
                            <td>{{ $dispute->paymentRequest->id }}</td>
                        </tr>
                        @if($currentUser->isMerchantInPayment($dispute->paymentRequest))
                        <tr>
                            <td class="tm-product-name">{{ __('Client') }}</td>
                            <td>{{ $dispute->paymentRequest->user->username }}</td>
                        </tr>
                        @else
                        <tr>
                            <td class="tm-product-name">{{ __('Merchant') }}</td>
                            <td>{{ $dispute->paymentRequest->merchant->user->username }}</td>
                        </tr>
                        @endif
                        @if($dispute->paymentRequest->item_list != null)
                            @foreach( json_decode($dispute->paymentRequest->item_list) as $item)
                                @foreach($item as $key => $value)
                                <tr>
                                    <td class="tm-product-name">{{ __('Item') }}&nbsp;#{{ $loop->parent->iteration }}</td>
                                    <td>{{ ucfirst($key) }}: {{ $value }}</td>
                                </tr>
                                @endforeach
                            @endforeach
                        @endif
                        <tr>
                            <td class="tm-product-name">{{ __('Price') }}</td>
                            <td>${{ $dispute->paymentRequest->getFinalPrice() }}</td>
                        </tr>
                        <tr>
                            <td class="tm-product-name">{{ __('Status') }}</td>
                            <td>{{ strtoupper($dispute->status) }}</td>
                        </tr>
                    </tbody>
                </table>
                @if(!$currentUser->isMerchantInPayment($dispute->paymentRequest) && $dispute->isOpen())
                <hr>
                <form action="{{ route('disputes.destroy', $dispute) }}" method="POST" role="form">
                @csrf
                    <input type="hidden" name="_method" value="DELETE" />
                    <button class="btn btn-block btn-danger" type="submit">{{ __('Delete Dispute') }}</button>
                @honeypot
                </form>
                @endif
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection